kind: pipeline
name: Publish to Docker Hub

steps:
- name: Build and Publish
  image: plugins/docker
  settings:
    repo: kudato/drone-ecs-deploy
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:7}

  when:
    branch:
    - master